### ISSUE TITLE
"Out of stack space" when using a combination of replaceable part and processContent

### ISSUE THREAD

**Issue by bobrov82** [aurelia/framework#699] opened 2017-01-19 07:35 UTC
**I'm submitting a bug report**

* **Library Version:**
1.0.7

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.4.5

* **NPM Version:**
3.10.6

* **JSPM OR Webpack AND Version**
0.16.34. Using Aurelia-CLI 0.18.0

* **Browser:**
IE 11 , propably other IE too. Not a problem in latest Chrome and Firefox.

* **Language:**
ESNext

**Current behavior:**
I get an error "Out of stack space"
![image](https://cloud.githubusercontent.com/assets/3773887/22097040/37d5c056-de1f-11e6-94e6-8ebe17381272.png)

This is because in IE in this code source.content is undefined and it get stuck in an infinite loop. In Chrome for example source.content is a document fragment.
![bug1](https://cloud.githubusercontent.com/assets/3773887/22097317/cc7e8624-de20-11e6-9772-66318539f6bf.PNG)

**Expected/desired behavior:**
https://gist.run/?id=3072405fd681de947591e6c37df311cc

I expected this to work in all browsers. I realize that I'm may be doing things in a non regular style.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
I'm building a small kind of CMS application for personal use. To be able to quickly create small sites.
It is just a matter of syntax where I would like to avoid typing `<template replace-part="content-part"></template>` everywhere I put my dynamic content. Thought I found a nice solution but doesn't work in IE.

**Comment by Zenorbi** [comment] 2017-01-31 21:39
This is probably a duplicate of https://github.com/aurelia/templating/issues/460 (same underlying problem)

**Closed** 2017-02-01 00:53 UTC
Labels: bug, duplicate
