### ISSUE TITLE
Dont load app.js in safari

### ISSUE THREAD

**Issue by sirgalleto** [aurelia/framework#402] opened 2016-04-19 21:41 UTC
Hi, actually im testing aurelia for create an app in my company, but when im testing on safari or mobile i dont see the execution of `app.js`whitout any error. 

app.js 
```
import {inject} from 'aurelia-framework';
import {ConsoleAppender} from 'aurelia-logging-console';
import {HttpClient} from 'aurelia-fetch-client';
import {Parse} from 'parse';
import {Keys} from './core/keys';
import {AuthorizeStep} from './auth/authorizeStep';
import {interceptor} from './core/interceptor';

@inject(Parse, Keys, ConsoleAppender, HttpClient)
export class App {
    constructor(parse, keys, consoleAppender, http) {
        alert('si');
        consoleAppender.info('', keys.name);
        parse.initialize(keys.parse.app, keys.parse.js);

        http.configure(config => {
            config.withBaseUrl(keys.api);
            config.rejectErrorResponses();
            config.withInterceptor(interceptor);
        });
    }

    configureRouter(config, router) {
        config.title = 'CityDrive | Socios';
        config.addPipelineStep('authorize', AuthorizeStep);
        config.map([
            {
                route: 'login',
                name: 'login',
                moduleId: 'auth/login',
                title: 'Iniciar sesión',
                nav: false,
                auth: false
            },
            {
                route: ['', 'home'],
                name: 'home',
                moduleId: 'welcome',
                title: 'Welcome',
                nav: true,
                auth: true
            },
            {
                route: 'users',
                name: 'users',
                moduleId: 'users',
                title: 'Github Users',
                nav: true,
                auth: true
            },
            {
                route: 'child-router',
                name: 'child-router',
                moduleId: 'child-router',
                title: 'Child Router',
                nav: true,
                auth: true
            }
        ]);

        this.router = router;
    }
}
```
I have any bad implementation or incompatibility?

**Comment by Vheissu** [comment] 2016-06-24 01:45
@sirgalleto Is this still an issue for you? On the surface, your code looks like. My hunch would be something you are importing is breaking things.

**Comment by LivesleyWA** [comment] 2016-06-26 00:31
It is an issue with me. Works on all browsers but Safari. 

There is an issue logged here which may be the culprit https://github.com/aurelia/fetch-client/issues/13

```
Error: (SystemJS) eval@[native code]
	promiseReactionJob@[native code]
	Evaluating http://www.trinovantes.net/source/bundles/app-build-js.js
	Error loading http://www.trinovantes.net/source/bundles/app-build-js.js
	Error loading http://www.trinovantes.net/source/ts/aurelia-application-configuration.js
error
promiseReactionJob
```

**Comment by EisenbergEffect** [comment] 2016-06-26 00:39
If you are using fetch-client, you will definitely need to include a fetch polyfill. There are several to choose from. See the docs here: http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/2 Try dropping in the polyfill and let us know if that fixes it for you.

**Comment by LivesleyWA** [comment] 2016-06-26 00:43
Not using the fetch client directly but I am going to drop in the polyfill just in case.

**Comment by LivesleyWA** [comment] 2016-06-26 22:47
Didn't do anything for me. I included the following in the load

```
SystemJS.import("../styles/ilexium-livery.min.css!css").then(function() {
    return SystemJS.import("whatwg-fetch");
}).then(function() {
    return SystemJS.import("aurelia-bootstrapper");
}).then(function() {
    return SystemJS.import("../js/noframework.waypoints.min");
}).then(function() {
    return SystemJS.import("bootstrap");
});
```
I am still getting the same issue. FWIW I am not convinced this is issues is directly associated with fetch. I commented everything out in aurelia-application-configuration.js but it still wouldn't load.

I also tried to include the module in aurelia-application-configuration.js as 

```
import "whatwg-fetch";
```
I will be pushing the latest code to a semi-public site if it helps. I don't want to publish the url yet but will provide on request.

**Comment by LivesleyWA** [comment] 2016-06-27 04:52
It's possible that this is being caused by the css. I re-wrote the application to use JQuery instead of Aurelia and I notice that, when loading in Safari I get some css warnings which I don't get in other browsers. I am loading the css library using SystemJS and I wonder if this is faulting as a result of the warnings. I can't test this right now but if I can I will do so.

May be worth adding a comment that loading the css using SystemJS may cause issues.

**Comment by EisenbergEffect** [comment] 2016-07-06 02:23
Closing this since it's likely not an Aurelia issue.

**Closed by EisenbergEffect** 2016-07-06 02:23 UTC

**Comment by sirgalleto** [comment] 2016-07-07 17:48
Thanks for the help

**Comment by LivesleyWA** [comment] 2016-07-08 17:09
For interest, I still think this is a systemjs issue but I am seeing it again on a minimal Aurelia project. I attach the project (rather large zip file I'm afraid)
[user-portal.zip](https://github.com/aurelia/framework/files/354734/user-portal.zip)
