### ISSUE TITLE
Allow for <script> tag in <template> to auto execute.

### ISSUE THREAD

**Issue by tnaigtnelis** [aurelia/framework#925] opened 2019-02-17 19:01 UTC
**I'm submitting a feature request**

* **Library Version:**
2.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
11.6.0

* **NPM Version:**
6.5.0-next.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI ^1.0.0-beta.13

* **Browser:**
Chrome 69.0.3497.106
* **Language:**
ESNext

**Current behavior:**
<script> tags nested in <template> tags do not execute when the view is loaded. I need this.

**Expected/desired behavior:**

* **What is the motivation / use case for changing the behavior?**

**Comment by bigopon** [comment] 2019-02-17 20:12
@tnaigtnelis The behavior you described is exactly the expected behavior. It's what `<template/>` was designed for. You can easily test this via pasting the folloing code into your console:
```js
document.body.innerHTML = '<template><script>alert("not")</script></template>';
```
You should see that though the script element is there, no alert box is shown.

**Comment by EisenbergEffect** [comment] 2019-02-17 22:38
Closing this since this behavior is by design per the HTML5 specification.

@tnaigtnelis I'm sure you've got a good reason for attempting this. If you can provide a few more details, we can probably help you find a workable solution. If that sounds good to you, please start a thread at https://discourse.aurelia.io/ and someone from our community will reach out.

**Closed by EisenbergEffect** 2019-02-17 22:38 UTC
