### ISSUE TITLE
click.delegate bindings cause top-level errors if the element they are attached to is removed from the DOM

### ISSUE THREAD

**Issue by hobbit125** [aurelia/framework#93] opened 2015-04-24 13:09 UTC
Minimal example:

https://gist.github.com/hobbit125/92cfd3e9daecca18071c

**Comment by zewa666** [comment] 2015-04-24 13:11
I think this might be a duplicate of this issue here https://github.com/aurelia/templating/issues/20

**Comment by hobbit125** [comment] 2015-04-24 13:38
Note: If you change the binding to click.trigger, the problem goes away.  This seems to be a problem specifically related to click.delegate event bubbling having the host element pulled out from under it..

Also, here's the specific error and call stack:

Uncaught TypeError: elem.getAttribute is not a functionSizzle.attr @ jquery.js:1446Sizzle.selectors.filter.ATTR @ jquery.js:1642i @ jquery.js:2143superMatcher @ jquery.js:2361Sizzle.select @ jquery.js:2531Sizzle @ jquery.js:850jQuery.event.handlers @ jquery.js:4475jQuery.event.dispatch @ jquery.js:4412jQuery.event.add.elemData.handle @ jquery.js:4116

**Comment by Bratn** [comment] 2015-04-24 16:01
I tried to make a Plunker repro, removed the underscorejs reference and instead used `splice` on index. Unfortunately (?) I can't see the above mentioned error. Am I missing something or why this different? 

http://plnkr.co/edit/kuhBBPoZiJpwcsaqdU78?p=preview

**Comment by sunjay** [comment] 2015-04-27 21:02
@EisenbergEffect You should delete the issue I created that @zewa666 referenced if you're going to keep this one because they're exactly the same.

**Comment by EisenbergEffect** [comment] 2015-07-22 01:30
This should be fixed in the latest.

**Closed by EisenbergEffect** 2015-07-22 01:30 UTC
Labels: bug, duplicate
