### ISSUE TITLE
injecting non existing class does not log any errors

### ISSUE THREAD

**Issue by tochoromero** [aurelia/framework#640] opened 2016-10-20 21:16 UTC
Hello guys. Today I encounter a very weird issue.

I had the following code:

```
import {inject} from "aurelia-framework";
import {TimesheetService} from "./timesheet-service";

@inject(TimesheetService, BucketService, AlertsService, DialogService)
export class Timesheet {
...
}
```

and then my timesheet-service.js

```
export class TimeSheetService {
...
}
```

Please note how I had the wrong casing, I was importing _Time**s**heetService_ but the actual class name was _Time**S**heetService_.

So yeah my bad, the problem is that there was no error in the console, there was no indicating anywhere that the class I was trying to import didn't exist on the file I specified. It took me a LONG time to realize I had a typo.

Shouldn't there be an error somewhere? I don't really know if the error should happen at import time or maybe at inject time, but somewhere there should be an exception thrown.

Or I'm missing something?

Thanks.

**Comment by EisenbergEffect** [comment] 2016-10-21 00:10
Part of this has to do with transpilation of modules by Babel. I'm not 100% sure if we can solve this. If there's a DI error, we do usually have something in the console. Can you create a reproduction for me so I can see what is going on?

**Comment by tochoromero** [comment] 2016-10-21 10:20
So I created a Gist Run with the code, and I DO get an error in the logs there, but of course I'm using preconcatenated scripts, so as you mentioned, it probably has to do with transpilation with Babel. On any case, this is the failing code.

https://gist.run?id=f8ede1fb1454bc2eb37f60951667a643

**Comment by tochoromero** [comment] 2016-10-21 15:18
So I found another instance where this is happen.
But this time I had a typo on my Template. I had `repeat.for="number in numbers`.
And there was no error in the console. I tried it on a GistRun and there, it shows me the expected error. But when I have that error on the Skeleton Navigation app running with gulp and ES6 the error is swallowed.

**Comment by EisenbergEffect** [comment] 2016-10-21 15:33
Hmm. I think this may be something else entirely. We recently had a small regression in our logging library that caused certain logged messages to not be displayed. I suspect that Gist has an older version prior to this regression and the skeleton you have has a newer version. We're updating the logging repo with the fix today or Monday.

**Comment by tochoromero** [comment] 2016-10-21 15:38
I'm actually glad is a regression and not something more obscure.
On the meantime, what library and to what version should I downgrade?
Thanks for the info Rob

**Comment by EisenbergEffect** [comment] 2016-11-19 20:05
Closing since the logger regression is fixed.

**Comment by tochoromero** [comment] 2016-11-19 20:55
Thanks!!

**Closed** 2016-11-19 20:55 UTC
Labels: bug
