### ISSUE TITLE
triggers vs delegates

### ISSUE THREAD

**Issue by chandmk** [aurelia/framework#89] opened 2015-04-20 14:50 UTC
Version: 0.12
``` javacript
export class Triggers {
  doSomething(evt){
    console.log(evt);
  }
}
```

``` html
<template>
  <section>
    <label>Triggers</label>
  <input id="triggers" change.trigger="doSomething($event)"  focus.trigger="doSomething($event)"  blur.trigger="doSomething($event)" />
  <!--<label>Delegates</label>
 <input id="delegates" change.delegate="doSomething($event)"  focus.delegate="doSomething($event)"  blur.delegate="doSomething($event)" /> -->
</section>
</template>
```

focus and blur events are not firing when I use triggers.  'change' is firing correctly. Documentation suggests that they can be used interchangeably.

**Comment by EisenbergEffect** [comment] 2015-04-22 05:40
This is something we'll be adding as part of a feature called "Binding Behaviors". The `trigger` behavior can be added to a two-way binding to change what events "trigger" the binding to update the model. In this case you would select the blur event.

**Comment by jdanyow** [comment] 2015-05-02 09:52
https://github.com/aurelia/templating-binding/issues/25

**Comment by Einarsson** [comment] 2015-06-03 13:57
@EisenbergEffect Is that implemented yet? We would like to tell an value.bind on an input to update the model on blur instead of immediately.

**Comment by EisenbergEffect** [comment] 2015-06-03 15:11
We have implemented a prototype, but we are waiting to add the features to master until after some critical internal changes the binging engine. Those changes should start happening in the next week. So hopefully, we can know them out quickly and get back to this feature.

**Comment by Einarsson** [comment] 2015-06-03 15:37
Great, will be looking forward to it.

**Comment by EisenbergEffect** [comment] 2015-07-22 01:30
Closing this issue since it's a duplicate of the binding behaviors issue which we are tracking elsewhere.

**Closed by EisenbergEffect** 2015-07-22 01:30 UTC
Labels: enhancement
