### ISSUE TITLE
Bluebird warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by crbranch** [aurelia/framework#351] opened 2016-03-04 18:55 UTC
While testing with MS Edge, I noticed major slowness until I added the bluebird.js library [as discussed here](http://blog.durandal.io/2015/12/17/more-aurelia-performance-bug-fixes-docs-and-typescript-awesome/).  That does seem to help speed things up tremendously in Edge.  However, ever since adding bluebird, I see messages in the console (Chrome, FireFox, IE11) that look like this:

    Warning: a promise was created in a handler but was not returned from it
        at AppRouter._createNavigationInstruction (http://localhost:8080/dist/aurelia-1df7aba477.js:23138:24)
        at AppRouter.loadUrl (http://localhost:8080/dist/aurelia-1df7aba477.js:23554:19)
        at BrowserHistory._loadUrl (http://localhost:8080/dist/aurelia-1df7aba477.js:9762:55)
        at BrowserHistory.activate (http://localhost:8080/dist/aurelia-1df7aba477.js:9687:21)
        at AppRouter.activate (http://localhost:8080/dist/aurelia-1df7aba477.js:23599:20)
        at http://localhost:8080/dist/aurelia-1df7aba477.js:23575:30
    From previous event:
        at http://localhost:8080/dist/aurelia-1df7aba477.js:23574:24
        at http://localhost:8080/dist/aurelia-1df7aba477.js:23578:17
        at AppRouter.registerViewPort (http://localhost:8080/dist/aurelia-1df7aba477.js:23585:11)
        at new RouterView (http://localhost:8080/dist/aurelia-1df7aba477.js:12735:19)
        at Object.Reflect.construct (http://localhost:8080/dist/aurelia-1df7aba477.js:8380:14)
        at Object.invokeWithDynamicDependencies (http://localhost:8080/dist/aurelia-1df7aba477.js:21973:20)
        at InvocationHandler.invoke (http://localhost:8080/dist/aurelia-1df7aba477.js:21959:168)
        at Container.invoke (http://localhost:8080/dist/aurelia-1df7aba477.js:22155:25)
        at ProviderResolver.get (http://localhost:8080/dist/aurelia-1df7aba477.js:18719:74)
        at Container.get (http://localhost:8080/dist/aurelia-1df7aba477.js:22108:23)
        at Container.elementContainerGet [as get] (http://localhost:8080/dist/aurelia-1df7aba477.js:18762:17)
        at HtmlBehaviorResource.create (http://localhost:8080/dist/aurelia-1df7aba477.js:20282:58)
        at applyInstructions (http://localhost:8080/dist/aurelia-1df7aba477.js:18824:33)
        at ViewFactory.create (http://localhost:8080/dist/aurelia-1df7aba477.js:19003:9)
        at HtmlBehaviorResource.create (http://localhost:8080/dist/aurelia-1df7aba477.js:20292:41)
        
        ......
I see 4 warnings like this when starting up the Typescript skeleton app (no code modifications).  [From the docs](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it), it sounds like it may be worth looking at.

**Comment by Gheoan** [comment] 2016-03-04 18:59
Duplicate of aurelia/skeleton-navigation#282.

**Closed** 2016-03-06 00:33 UTC
Labels: duplicate
