### ISSUE TITLE
Link does not work on Hub

### ISSUE THREAD

**Issue by Narven** [aurelia/framework#705] opened 2017-01-29 16:33 UTC
In:

`http://aurelia.io/hub.html#/doc/article/aurelia/i18n/latest/i18n-with-aurelia/5`

The link on  the line: `The object passed to t-params is a complex object explained in the next section`

That was supposed to go to: http://aurelia.io/hub.html#complex-objects-for-variables

does not work

**Comment by AshleyGrant** [comment] 2017-01-29 16:46
@zewa666 would you please check in to this and update the link. I think you asked about this type of linking in the chat room?

**Comment by zewa666** [comment] 2017-01-29 17:39
Yep thanks for reporting. The issue is that the hub does not support linking to a 3rd level entry. I'll rewrite the section to make sense without a link

**Comment by AshleyGrant** [comment] 2017-01-29 18:21
@EisenbergEffect looks like this one can be assigned to @zewa666

**Comment by zewa666** [comment] 2017-01-29 21:45
Oh I think that's related to this issue https://github.com/aurelia/i18n/issues/190 the hub just hasn't been updated

**Comment by EisenbergEffect** [comment] 2017-01-29 21:48
Likely. I'm behind on docs updates. I'll close this out.

**Closed by EisenbergEffect** 2017-01-29 21:48 UTC
Labels: bug, documentation
