### ISSUE TITLE
Aurelia not displaying correct representation of array in UI after removing item with lodash.

### ISSUE THREAD

**Issue by 4imble** [aurelia/framework#813] opened 2017-08-09 13:42 UTC
**I'm submitting a bug report**

* **Library Version:**
+-- aurelia-bootstrapper@2.1.1
|  -- aurelia-framework@1.1.4

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v6.11.1

* **NPM Version:**
5.3.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.30.1

* **Browser:**
all 

* **Language:**
TypeScript

**Current behavior:**
```javascript
    `_.pull(array, item);` //removes item and fails to update the ui
    `_.remove(array, item);` //removes item and fails to update the ui
    `this.stack.shift();` //removes first item and updates the ui

    const index = array.indexOf(item);
     if (index !== -1) {
        this.splice(index, 1);
     } //correctly removes first item and updates the ui
```

**Expected/desired behavior:**
Both `_.pull` and `_.remove` mutate the array and so I would expect it to update the UI when used. 

* **What is the motivation / use case for changing the behavior?**
At the moment I have to resort to writing my own extensions around Array in order to make this work. It would be nice to know that I can have confidence in using all of the convenience methods of other libraries like lodash.
https://stackoverflow.com/questions/40508727/aurelia-not-displaying-correct-representation-of-array-after-removing-item

**Comment by gheoan** [comment] 2017-08-10 11:54
Duplicate of https://github.com/aurelia/binding/issues/597.

**Comment by 4imble** [comment] 2017-08-10 12:10
Ahh, sorry missed that. What's the best way to ensure lodash is loaded after aurelia? I currently just have it in the bundling.

**Comment by gheoan** [comment] 2017-08-10 13:36
Not sure how would you do that for the CLI. Try changing the order in aurelia.json so that lodash is the last dependency.

**Comment by Alexander-Taran** [comment] 2018-03-17 01:43
stale with no answer

**Comment by EisenbergEffect** [comment] 2018-03-17 02:16
Closing since there's a workaround via loading lodash after Aurelia.

**Closed by EisenbergEffect** 2018-03-17 02:16 UTC
