### ISSUE TITLE
View files not resolving correctly if located in jspm_packages

### ISSUE THREAD

**Issue by Aaike** [aurelia/framework#39] opened 2015-02-11 14:02 UTC
I have finally been able to register my behaviours and custom elements using a plugin.
I have now moved all these files into a seperate package that is installable using jspm.

So the files now live in jspm_packages/github/aaike/aurelia@0.0.1/* intead of the src folder.
this is mapped as 'aaike': "github:aaike/aurelia@0.0.1"

i am registering the plugin from the package like this .plugin('aaike/ui-plugin')

This correctly points to the plugin file of the package in the jspm_package dir,
from there javascript files for the behaviours and elements are also resolved correctly

meaning this all works...
except ... when a custom element has a view file...

so all my custom element are working except for the ones that have a html file
The html import does not seems to correctly take the jspm config into account

my js files are correctly resolving like this :
http://localhost:9000/jspm_packages/github/aaike/aurelia@0.0.1/widgets/editor.js

but the html files are resolving to the dist like this :
http://localhost:9000/dist/github/aaike/aurelia@0.0.1/widgets/editor.html

so it seems the package name is correctly converted from aaike to github/aaike/aurelia@0.0.1
but it keeps looking inside the dist directory...

@zewa666 suggesting trying the `convertModuleIdToViewUrl` method or  `getViewStrategy`
But...
`convertModuleIdToViewUrl` only seems to works for ViewModels, not for custom elements or behaviours.
and the `getViewStrategy` also seems to be only for ViewModels

I can change the view file my behaviour or custom element is using with the `.useView()` method on the metadata behaviour. but this also always uses dist as the baseUrl.

**Comment by Aaike** [comment] 2015-02-11 14:03
I should also note that in the standard skeleton-nav, the loading of js files in jspm_packages would not work out of the box.
if i were to use `baseUrl` for systemjs like the skeleton-nav does, then the loading of js files in jspm_packages would also not work, because everything is based of the `baseUrl`.

so using `baseViewUrl ` solved the loading of javascript files for my package.

But because of this the view files always seem to point to the dist directory while these should point to the jspm_directory

**Comment by EisenbergEffect** [comment] 2015-02-11 14:10
We are working in improvements to the loader that should resolve this. It is tracked elsewhere.

**Comment by Serhioromano** [comment] 2015-02-12 10:33
@Aaike can you show your code example. I would like to know how to create Aurelia modules that could be installed with jspm.

Thank you.

**Comment by Aaike** [comment] 2015-02-12 11:35
@Serhioromano please check out the JSPM documentation on [how to configure packages for JSPM](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm)

once you have that simply load your modules using the import statement like any other jspm installable package

**Comment by yelvert** [comment] 2015-02-16 01:06
Has this been solved? And, what is this a duplicate of?

**Comment by EisenbergEffect** [comment] 2015-03-02 19:04
This should now be fixed on master. It's going out in the next release. Essentially, our view loading now goes through System.js and Require.js first in order to correctly map paths. Also, our plugin api has changed in order for us to be able to get the proper module id info.

**Closed by EisenbergEffect** 2015-03-02 19:04 UTC
Labels: duplicate

**Comment by Aaike** [comment] 2015-03-02 20:52
Fantastic !

**Comment by embedthis** [comment] 2016-03-07 23:36
Does this also fix the case where are required CSS sheet cannot do relative url() sourcing. E.g.

```
            <require from="semantic-ui/semantic.css"></require>
```

where semantic.css then does:

```
@font-face {
  font-family: 'Icons';
  src: url("themes/default/assets/fonts/icons.eot");
```

The "themes/default/assets/fonts/icons.eot" cannot be found when building because the base directory does not seem to be set correctly.

**Comment by EisenbergEffect** [comment] 2016-03-08 01:11
When require a css file, the urls in that css file are relative to the view that it is imported inside of. For scenarios like this, I would recommend just adding it as a link in your html file. You could also use the system.js css plugin to import the css in your main.js file if you preferred.
