### ISSUE TITLE
repeat.for renders same item twice

### ISSUE THREAD

**Issue by powerbuoy** [aurelia/framework#830] opened 2017-10-06 11:41 UTC
I have a strange issue where when I try to push an empty object to an array that is rendered in my view - the newly pushed element is rendered twice.

The duplicate element is in fact the exact same element as the previous one (if I change the first the second also changes).

I'm unable to reproduce this in a GistRun (perhaps version differences) - but I have managed to reproduce it in a completely new Aurelia CLI project with the following code:

**app.js**

```js
export class App {
	constructor () {
		this.items = [];
		this.editing = false;
	}

	// Toggle the edit form
	toggleEditing () {
		this.editing = !this.editing;

		// Also add a new item
		if (this.editing) {
			this.items.push({}); // NOTE: This is where things go wrong
		}
	}
}
```

And this view:

**app.html**

```html
<template>

	<template if.bind="!editing">
		<h2>${items.length} items!</h2>
		<ul>
			<li repeat.for="item of items">
				${item.name}
			</li>
		</ul>
		<button click.delegate="toggleEditing()">Edit</button>
	</template>

	<template if.bind="editing">
		<ul>
			<li repeat.for="item of items">
				<input type="text" value.bind="item.name">
			</li>
		</ul>
		<button click.delegate="toggleEditing()">Save</button>
	</template>

</template>
```

My `package.json` looks like this (for version info):

**package.json**

```json
{
  "name": "autest",
  "description": "An Aurelia client application.",
  "version": "0.1.0",
  "repository": {
    "type": "???",
    "url": "???"
  },
  "license": "MIT",
  "dependencies": {
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-animator-css": "^1.0.2",
    "bluebird": "^3.4.1",
    "requirejs": "^2.3.2",
    "text": "github:requirejs/text#latest"
  },
  "peerDependencies": {},
  "devDependencies": {
    "aurelia-cli": "^0.31.3",
    "aurelia-testing": "^1.0.0-beta.3.0.1",
    "aurelia-tools": "^1.0.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "minimatch": "^3.0.2",
    "through2": "^2.0.1",
    "uglify-js": "^3.0.19",
    "vinyl-fs": "^2.4.3",
    "babel-eslint": "^6.0.4",
    "babel-plugin-syntax-flow": "^6.8.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-amd": "^6.8.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.10.3",
    "babel-plugin-transform-flow-strip-types": "^6.8.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-1": "^6.5.0",
    "babel-polyfill": "^6.9.1",
    "babel-register": "^6.24.0",
    "gulp-babel": "^6.1.2",
    "gulp-eslint": "^2.0.0",
    "gulp-htmlmin": "^3.0.0",
    "html-minifier": "^3.2.3",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-babel-preprocessor": "^6.0.1",
    "browser-sync": "^2.13.0",
    "connect-history-api-fallback": "^1.2.0",
    "debounce": "^1.0.2",
    "gulp-changed-in-place": "^2.0.3",
    "gulp-plumber": "^1.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.0.0-alpha",
    "gulp-notify": "^2.2.0",
    "gulp-watch": "^4.3.11"
  }
}
```

Maybe it's something obvious I've missed? But it seems like a genuine bug to me.

I'm attaching my example app as well which exhibits the bug and can be run in Firefox directly. Just click "Edit" and two input fields will be shown instead of one - changing one actually changes both.

[autest.zip](https://github.com/aurelia/framework/files/1362545/autest.zip)

**Comment by bigopon** [comment] 2017-10-07 12:30
If you are using `templating-resources@1.5.1`, possibly it's related to aurelia/templating-resources#317

**Comment by powerbuoy** [comment] 2017-10-09 12:34
@bigopon I am indeed using 1.5.1. I'm not sure they're related though?

I've simplified my example code slightly. And FYI I'm using Aurelia CLI 0.31.3 (which I believe is the latest version?)

**Comment by jwx** [comment] 2017-10-09 13:22
Do you get the same issue if you remove the if-part from the example?

**Comment by powerbuoy** [comment] 2017-10-09 13:32
@jwx I do not. Removing the `if` solves the issue. Also switching to `show` instead of `if` solves it - however, `show` does not appear to work with `<template>`.

**Comment by jwx** [comment] 2017-10-09 14:54
@powerbuoy Then problem is probably with `if`, so yeah, at least related to it. There's a fix in that one that you could try and see if it helps.

**Comment by powerbuoy** [comment] 2017-10-11 10:24
Ok, honestly I'm not sure how I would implement the fix? You mean the `ifCore` override right?

I went ahead and updated all Aurelia packages today (I basically deleted `node_modules` and just reinstalled everything with my `package.json` pointing to the latest versions of all packages). I've also got the latest version of node and npm.

However, I still get the same issue as above and now new issues are introduced that also seem related to `if.bind`. When toggling the visibility of a `<template>` things (bindings) simply stop working. My app is littered with this code so it isn't really feasible for me to change it all now.

I'm guessing this is the same issue as mentioned in https://github.com/aurelia/templating-resources/issues/317 and https://github.com/aurelia/templating-resources/issues/315

How does one go about rolling back to a previous version? Most of the Aurelia packages aren't in `package.json` so not sure how their version numbers are controlled?

**Comment by mreiche** [comment] 2017-10-11 11:59
> How does one go about rolling back to a previous version? Most of the Aurelia packages aren't in package.json so not sure how their version numbers are controlled?

I've spent hours trying to rollback to a previous version with JSPM. Without luck. Problem was, that I'm not able to LOCK a specific version of templating-resources and it's gonna overridden by the dependency tree: aurelia-materialize-bridge -> aurelia-framework -> aurelia-templating -> aurelia-templating-resources.

If you figured out how to rollback, tell me, I will really appreciate that!

**Comment by powerbuoy** [comment] 2017-10-11 12:33
I've pretty much swapped out all my `if.bind`:s to `show.bind`:s instead and while it meant I had to re-code some stuff that will require rigorous testing it seems to be working at first glance for now at least.

Here's hoping for an official patch soon :)

**Comment by mreiche** [comment] 2017-10-11 12:53
> I've pretty much swapped out all my if.bind:s to show.bind:s instead and while it meant I had to re-code some stuff that will require rigorous testing it seems to be working at first glance for now at least.

Yes, but that doesn't help for ``repeat``.

**Comment by powerbuoy** [comment] 2017-10-19 17:15
I see there's a fix for both https://github.com/aurelia/templating-resources/issues/317 and https://github.com/aurelia/templating-resources/issues/315 out. However, my `repeat.for` issue, as well as the issues I have with `if.bind` are not solved by the new release.

I managed to reproduce my issue in gist.run now as well; https://gist.run/?id=af8b192abd4ce89a62fe1383dba79d93

Changing from `if.bind` to `show.bind` solves it there too. I'm not 100% sure that gist is using the latest version of everything, but this same thing happens locally with everything updated (`aurelia-templating@1.6.0`)

**Comment by StrahilKazlachev** [comment] 2017-10-19 17:31
@powerbuoy Not released yet.

**Comment by powerbuoy** [comment] 2017-10-19 17:33
Ah ok, my bad :) I guess the fix is in templating-resources?

**Comment by StrahilKazlachev** [comment] 2017-10-19 17:38
Yes.

**Comment by dkent600** [comment] 2017-10-24 16:44
This is happening to me, but has nothing to do with if or show:

The result is that the content is rendered twice for each array item that is added using `myArray.push(newItem)` after the view has been bound.

What is really weird is that when I do a production build, the bug goes away. 

```
<div repeat.for='item of myArray'>
    Item
</div> 
```

**Comment by dkent600** [comment] 2017-10-24 17:44
Wow, I just updated to v1.4.0 of templating-resources and now for every item in the array I see four instead of two!

**Comment by dkent600** [comment] 2017-10-24 20:05
OK, referring to my repro case just above ^^^, I figured out how to make the bug go away, even in my dev build.  First, note that this applies to aurelia-typescript-webpack.  The change is in webpack.config.js.

The original, that works, looks like this in the `entry` property:

```
entry: {
    app: ['aurelia-bootstrapper'],
    vendor: ['bluebird', 'jquery', 'bootstrap'],
  }
```

What doesn't work, and causes this bug to happen in the development build, is the following:

```
    entry: {
      app: ['aurelia-bootstrapper'],
      vendor: [
        'bluebird', 
        'aurelia-templating', 
        'aurelia-binding', 
        'aurelia-router', 
        'aurelia-templating-binding', 
        'aurelia-polyfills',
        'aurelia-event-aggregator',
        'bootstrap', 
        'jquery',
        ],
  }
```

**Comment by esmoore68** [comment] 2017-11-08 22:28
I'm still seeing this issue in my app, using aurelia-templating-resources@1.5.4. This bug is causing me to have to jump through all kinds of hoops to avoid.

**Comment by bigopon** [comment] 2017-11-08 22:45
@esmoore68 does it occur with `templating-resources@1.4.0` ?

@jods4 If it's ok with `1.4.0`, then i think repeat has some issue, not the `if`

**Comment by StrahilKazlachev** [comment] 2017-11-08 22:52
I just tried a *cli* build with no problems - `aurelia-templating-resources@1.5.4`.
@esmoore68 please provide a repro of the problem you are facing.

**Comment by dkent600** [comment] 2017-11-09 00:42
@StrahilKazlachev You might be able to repro with a webpack.config such as I described above.

**Comment by esmoore68** [comment] 2017-11-09 14:16
@StrahilKazlachev, the actual cases (there are many) in my app might be difficult to distill, but I can easily recreate using the test case created by @powerbuoy above. 

@bigopon- It still happens with templating-resources@1.4.0.

Aurelia entries from my packages.json:


```
    "aurelia-animator-css": "^1.0.1",
    "aurelia-binding": "^1.5.0",
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-dialog": "^1.0.0-rc.1.0.3",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-fetch-client": "^1.1.1",
    "aurelia-http-client": "^1.0.4",
    "aurelia-oauth": "github:esmoore68/aurelia-oauth",
    "aurelia-templating": "^1.6.0",
    "aurelia-templating-resources": "^1.4.0",
    "aurelia-validation": "^1.0.0",
```
I am using Typescript and Webpack.

related settings from my webpack.config:

```
const {AureliaPlugin, ModuleDependenciesPlugin } = require("aurelia-webpack-plugin");

module.exports = {
  entry: "aurelia-bootstrapper",
  },
```

**Comment by BlueManiac** [comment] 2017-11-13 09:23
I also have this problem using a simple

<tr repeat.for="op of operations">
  <td>${op.operationId}</td>
</tr>

After I have pushed two items the resulting html is:

<tr>
	<td>1</td>
</tr>
<tr>
	<td>2</td>
</tr>
<tr>
	<td></td>
</tr>
<tr>
	<td></td>
</tr>

so the duplicated items have no contents.

using:
"aurelia-bootstrapper": "^2.0.1",
"aurelia-fetch-client": "^1.1.3",
"aurelia-framework": "^1.1.5",
"aurelia-loader-webpack": "^2.0.0",
"aurelia-pal": "^1.4.0",
"aurelia-router": "^1.4.0",
"aurelia-templating-resources": "^1.5.4",

**Comment by bigopon** [comment] 2017-11-13 09:31
I still cant reproduce it. @esmoore68 @BlueManiac can you confirm that your `templating-resources@1.5.4` is used ? Maybe check inside `node_modules/aurelia-bootstrapper` to see if there is any `node_modules` with `templating-resources` there.

**Comment by StrahilKazlachev** [comment] 2017-11-13 10:25
You can do `npm ls aurelia-templating-resources`.

**Comment by BlueManiac** [comment] 2017-11-13 11:17
Seems to be correct. I removed dist and rebuilt the application, same thing.

```npm ls aurelia-templating-resources```

```
+-- aurelia-bootstrapper@2.1.1
| `-- aurelia-templating-resources@1.5.4  deduped
`-- aurelia-templating-resources@1.5.4
```

An interesting note is that if I update the view using HMR the display problem goes away until I add more rows.

**Comment by esmoore68** [comment] 2017-11-13 14:56
`npm ls aurelia-templating-resources
`-- aurelia-templating-resources@1.5.4`

I verified that the version of aurelia-templating-resources being built in to my webpack bundle includes the code changed in  the fix that @jods4 made to this module that I _think_ was supposed to address this issue?

https://github.com/aurelia/templating-resources/commit/9548e16bc9ea574bd2e69b65cc5772c341de653a#diff-bbce44daacb259a7b129c4fa0d062406

To be clear, I am using @powerbuoy's test case, but am seeing this behavior all over my app.

**Comment by StrahilKazlachev** [comment] 2017-11-13 21:57
Here is how I reproduced it:
1. Create a new `webpack`/`requirejs` project using `aurelia-cli`.
2. Copy&Paste the `app.js/html` from the first post.

What I saw:
1. Creating new array, lets say like this `this.items = [...this.items, [{}]];`, instead of mutating the current one makes it work as expected.
2. When using `.push` the `ChangeRecord`s seem correct to me. Here is one for the 3rd addition:
```json
[{"index":2,"removed":[],"addedCount":1}]
```
3. If the element with the `repeat` is **not** a descendant of an element with an `if`, all works as expected.
4. I see the same behavior with `aurelia-templating-resources@1.4.0`.

**Comment by jods4** [comment] 2017-11-13 22:03
> I see the same behavior with aurelia-templating-resources@1.4.0.

Quite important point to notice because the timing is unlucky. 1.5 contained changes in `if` with the introduction of `else` and a few important bugs that got fixed in 1.5.4.

If it reproduces with `templating-resources@1.4.0` it means the bug is not in the recent `if` changes but was there before.

**Comment by bigopon** [comment] 2017-11-14 13:31
The issue is because `instanceChanged` and `instanceMutated` happen at the same time by `this.items.push({})` causing repeat to add duplicated view. Temporary workaround is to make sure they don't happen in the same micro task flush via:

```js
  // Toggle the edit form
  toggleEditing () {
    this.editing = !this.editing;

    // Also add a new item
    if (this.editing) {
      setTimeout(() => this.items.push({}));
    }
  }
```

I'm not sure how to fix this yet 😅

**Comment by jods4** [comment] 2017-11-14 21:53
A little out of the blue because I haven't looked at the code in depth but maybe:
`instanceMutated` should look at what the current instance in the repeat viewmodel is. If it's not the one being mutated, there is a race condition in the notification microtasks and the mutation should be ignored.

**Comment by pkkummermo** [comment] 2017-11-15 18:29
I've had the same issue, but not in 1.4.0 of templating-resources (see https://github.com/aurelia/templating/issues/580 for more details)

**Comment by cbrownie** [comment] 2017-11-15 22:58
My team has also encountered the issue that @BlueManiac has outlined exactly. We were battling with it for awhile, and ending up reverting all our package.json to an earlier working state from about a month ago to get around it. Would be very interesting in a fix.

**Comment by StrahilKazlachev** [comment] 2017-11-15 23:09
@cbrownie Could you post the versions of `aurelia-templating` and `aurelia-templating-resources` with which you don't get this issue?

**Comment by cbrownie** [comment] 2017-11-16 14:34
@StrahilKazlachev 
These are the aurelia package versions we were using that produced the issue with repeaters and other odd errors.

    "aurelia-animator-css": "^1.0.4",
    "aurelia-api": "^3.1.1",
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-dependency-injection": "^1.3.2",
    "aurelia-dialog": "^1.0.0-rc.1.0.3",
    "aurelia-event-aggregator": "^1.0.1",
    "aurelia-fetch-client": "^1.1.3",
    "aurelia-framework": "^1.1.5",
    "aurelia-history-browser": "^1.1.0",
    "aurelia-http-client": "^1.2.1",
    "aurelia-i18n": "^1.6.2",
    "aurelia-loader-default": "^1.0.3",
    "aurelia-logging": "^1.3.1",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal": "^1.4.0",
    "aurelia-pal-browser": "^1.3.0",
    "aurelia-path": "^1.1.1",
    "aurelia-permission": "^0.5.3",
    "aurelia-polyfills": "^1.2.2",
    "aurelia-router": "^1.4.0",
    "aurelia-templating-binding": "^1.4.0",
    "aurelia-templating-resources": "1.5.3",
    "aurelia-templating-router": "^1.2.0",
    "aurelia-validation": "^1.1.2",

This is a seemingly stable excerpt of our package.json from a couple months ago.

    "aurelia-animator-css": "^1.0.0",
    "aurelia-api": "^3.1.1",
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-dependency-injection": "^1.0.0",
    "aurelia-dialog": "^1.0.0-rc.1.0.3",
    "aurelia-event-aggregator": "^1.0.0",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-framework": "^1.0.0",
    "aurelia-history-browser": "^1.0.0",
    "aurelia-http-client": "^1.0.0",
    "aurelia-i18n": "^1.1.2",
    "aurelia-loader-default": "^1.0.0",
    "aurelia-logging": "^1.0.0",
    "aurelia-logging-console": "^1.0.0",
    "aurelia-pal": "^1.0.0",
    "aurelia-pal-browser": "^1.0.0",
    "aurelia-path": "^1.0.0",
    "aurelia-permission": "^0.5.2",
    "aurelia-polyfills": "^1.0.0",
    "aurelia-router": "^1.0.0",
    "aurelia-templating-binding": "^1.0.0",
    "aurelia-templating-resources": "^1.0.0",
    "aurelia-templating-router": "^1.0.0",

I can't figure out exactly why this revert is fixing the issue because our use of `^` in both instances should be grabbing the same version of `aurelia-templating`, and `aurelia-templating-resources`.

On a second look the only package that really changed a major version in our package.json was webpack: "webpack": "^3.8.1" --(back to)--> "webpack": "^2.6.1".

We also upgraded npm itself from a 3.x.x to a 5.x.x version on our Jenkins build server that handled running npm install.

**Comment by StrahilKazlachev** [comment] 2017-11-16 15:08
@cbrownie Thanks, that is really strange. I really wanted to easily pinpoint when the problem was introduced 😅.
Also Webpack should not be an issue since I reproduced it with RequireJS.

**Comment by PhanindraKumar** [comment] 2017-12-28 07:10
Any update on this. I am trying to call a function in repeat.for. its been called twice, I cant able to replicate it in gist . One interesting thing i observed. when we set break-point on called function. it works fine. 

I am using aurelia-templating-resources@1.5.4

**Comment by pkkummermo** [comment] 2018-01-02 08:29
I've had to temporary revert the version due to the numerous places it breaks within our application. Hopefully this issue will be fixed and I can update to the newest :+1: 

Just to clarify what I'm reverting:
```
-        "aurelia-templating": "1.6.0",
-        "aurelia-templating-binding": "1.4.0",
-        "aurelia-templating-resources": "1.5.4",
+        "aurelia-templating": "1.4.2",
+        "aurelia-templating-binding": "1.3.0",
+        "aurelia-templating-resources": "1.4.0",
```

After this it works perfectly again.

**Comment by Alexander-Taran** [comment] 2018-03-19 14:32
@pkkummermo can you check out if it is resolved with latest versions?

**Comment by pkkummermo** [comment] 2018-03-20 06:39
Sure, I'll do an upgrade test today :)

**Comment by roy46** [comment] 2018-03-20 13:38
Hi. I am not sure if i am experiencing exactly the same issue detailed in this thread. However, I have an issue with the `repeat.for` attribute rendering twice in an Aurelia App/Widget (creating via the `bootstrap((aurelia: Aurelia) => { //.... })`) inside another Aurelia app.

It's almost as if Aurelia is proxying the array functions (push, splice etc) twice. Although it's worth noting that the unexpected HTML elements have no view model (aka they render no values to the DOM). Just like @BlueManiac mentioned in his post dated 13 Nov 2017.

If I create a new array instead of using push, splice, unshift everything works fine. Example that works as expected:

```
export class BugFixForRepeatingArrayValueConverter {
    public toView(array: any[]) {
        return [].concat(array);
    }
}

<div repeat.for="i of myArray | bugFixForRepeatingArray">
    ${ i }              
</div>
```

using: 
``` 
aurelia-binding: 1.7.1
aurelia-templating: 1.7.0 
aurelia-templating-binding: 1.4.1
aurelia-templating-resources: 1.6.0```

Note: if this widget is not hosted in another Aurelia app everything works as expected.

**Comment by Alexander-Taran** [comment] 2018-03-20 13:45
@roy46 could you describe a bit more your double aurelia setup?

**Comment by roy46** [comment] 2018-03-20 14:28
I have a widget class that exposes an `init()` to start up the component:
```export default class MyWidget {


	constructor(private config: UniCommsWidgetConfig) {
	}

	public init() {
		bootstrap((aurelia: Aurelia) => {
			aurelia.use
				.standardConfiguration()
				.developmentLogging();

			aurelia.start().then(() => {
				aurelia.setRoot(PLATFORM.moduleName("widget/app-widget"), this.config.element);
			});
		});
	}
}```

**Comment by roy46** [comment] 2018-03-20 14:33
I have a widget class that exposes an `init()` to start up the component:
```export default class MyWidget {
	constructor(private config: WidgetConfig) {
	}

	public init() {
		bootstrap((aurelia: Aurelia) => {
			aurelia.use
				.standardConfiguration()
				.developmentLogging();

			aurelia.start().then(() => {
				aurelia.setRoot(PLATFORM.moduleName("widget/app-widget"), this.config.element);
			});
		});
	}
}
```
Then I have created a test harness (another Aurelia app) that imports and uses that widget. In the test harness I created a wrapper component:
```export class WidgetWrapper {

    @bindable public property1: string;
    @bindable public property2: string;
    private _widget: MyWidget ;

    constructor(private element: Element) { }

    public attached() {
        this._widget = new MyWidget({
            element: <HTMLElement>this.element,
            property1: this.property1,
            property2: this.property2
        });

        this._widget.init();
    }
}```

**Comment by Alexander-Taran** [comment] 2018-03-20 15:15
@roy46 can't explain why, but it looks like a way to disaster (-:

**Comment by pkkummermo** [comment] 2018-03-20 20:01
@Alexander-Taran I tried updating to the newest versions, ie
```
    "aurelia-templating": "^1.7.0",
    "aurelia-templating-binding": "1.4.1",
    "aurelia-templating-resources": "1.6.0",
```
and I'm afraid the problem still persists. Is there any deps I should be updating alongside these which might cause interference?

**Comment by Alexander-Taran** [comment] 2018-04-01 12:51
Ok then. Got nothing to add for the moment.

**Comment by pkkummermo** [comment] 2018-04-01 16:57
OK. Went through several stuff now.

1. Went to the CLI to see if I was missing any dependencies. Added several (which I guess was mostly implicit within the other existing deps).
2. Updated _all_ aurelia-related packages with the exception of the `aurelia-webpack-plugin` (haven't updated to WP4 yet. 
3. Still no go. 

Example of a simple dialog with two pushes over time:
![image](https://user-images.githubusercontent.com/1799456/38175545-635ba3b8-35de-11e8-8667-445da4987e17.png)

As you see it still doubles up with an empty item in the array. Let me know if you want me to debug anything deeper @Alexander-Taran

**Comment by Alexander-Taran** [comment] 2018-04-01 22:00
@pkkummermo will do.. maybe.. if.. and when (-:

**Comment by amartens181** [comment] 2018-04-05 21:25
In some components, if I put the function to set the array in the bind method, it will duplicate the first half items. It works correctly in the attached method.

**Comment by mikeesouth** [comment] 2018-05-08 19:42
Any updates here? I got the same issue. I have a repeater like so:
```
<div repeat.for="item of myArray">
  ${item.name}
</div>
```

I subscribe to the EventAggregator and when an updated array is sent in an event I update myArray like this:
```
this.myArray.splice(0, this.myArray.length);
updatedArray.forEach(c => this.myArray.push(c));
```

I specifically did this to not reassign the array but rather clear it and update it. This was to prevent the binding from "being lost" in earlier versions. This causes empty items in my repeater, just like @pkkummermo describes (ITEM1, ITEM2, EMPTY, EMPTY). I can fix this by replacing my splice + push logic to a reassign, like this:
`this.myArray = [...updatedArray];`

Then it works. But I have to this in several places in my code and it's quite difficult to find them.

Any news on this issue? Will it be fixed or should I just start to convert to reassigning my arrays that I use for repeaters?

**Comment by EisenbergEffect** [comment] 2018-05-08 22:28
@bigopon I think this would be a great issue for you to look into :)

**Comment by bigopon** [comment] 2018-05-09 13:40
I have fix this issue by instructing `Repeat` to ignore mutation while processing instance change (main changes can be found at https://github.com/bigopon/templating-resources/blob/d4ff656a44fd2c2fc4d7b5770f6c036723325b60/src/repeat.js#L138-L142). Code:

```js
    this.ignoreMutation = true;
    this.strategy.instanceChanged(this, items);
    this.observerLocator.taskQueue.queueMicroTask(() => {
      this.ignoreMutation = false;
    });
```

With the above changes, the issue in @powerbuoy 's demo is fixed, demo at https://gist.run/?id=56d85dc0c87214d1f79b5b284c76308a . Though I haven't been able to create a test for it, I built the code and created a branch at https://github.com/bigopon/templating-resources/tree/fix-repeat so folks who need it can use it to workaround if needed.

@EisenbergEffect  @jdanyow @fkleuver / all Would love to have some help on the test [here](https://github.com/bigopon/templating-resources/blob/fix-repeat/test/repeat-integration.spec.js#L1034-L1055) (it always got the number of elements right even without the changes)

**Comment by Alexander-Taran** [comment] 2018-05-14 09:41
@bigopon could it also improve the rendering perf for patial updates?

**Comment by bigopon** [comment] 2018-05-14 10:36
@Alexander-Taran  That's a nice suggestion. Not sure if ignoring mutation while processing mutation will cause any issue. Will need to investigate a bit

**Comment by bigopon** [comment] 2018-05-14 10:43
@Alexander-Taran To answer the main question: I don't think it would have any impact on that.

**Comment by Alexander-Taran** [comment] 2018-05-14 11:01
@bigopon this thread: https://github.com/krausest/js-framework-benchmark/pull/376#issuecomment-388396221
last 4-5 comments.
Sometimes partial update benchmark produces way more than 1-2 paints.. and the resultant timing is off charts.

**Comment by zefubachs** [comment] 2018-06-27 06:43
I just started using Aurelia using aspnetcore, aurelia-cli and the todo tutorial:
Each time i add a todo to the array it renders another (empty) `<li>` element after the 'correct' elements of the array.

When i log the amount elements in the array, it shows the correct amount.

Initially i added aurrelia to an existing aspnetcore project but later i reproduced thesame with a simple emtpy aspnetcore project using Visual Studio and then used aurelia-cli using the following properties:
- typescript
- less
- aspnetcore
- webpack
- no minification etc, ...
- restore dependencies

I have no experience with webpack and only little experience with SPA's (used angular1 a while back and tried vuejs) so much of the files created by the cli is like a black box to me.
If any info is required, i'll be happy to supply it.

**Comment by zefubachs** [comment] 2018-06-27 08:43
Managed to fix it by updating nodejs to the latest version.
After that removing the `node_modules` folder and manually executing `npm install`.

**Comment by mikeesouth** [comment] 2018-07-10 08:30
@shunty-gh Have you tried a fresh `npm install`? Remove node_modules and package-lock.json and then a fresh npm install with the new package versions from your updated package.json. I had the same issue but a clean npm install solved the problem.

**Comment by shunty-gh** [comment] 2018-07-10 08:52
...and I can confirm that using a local (non npm) copy of aurelia-breeze and, thus, ignoring the outdated dependencies allows the Array.push approach to work fine. And makes my bundle a little smaller too :-)

**Comment by shunty-gh** [comment] 2018-07-10 09:17
@mikeesouth Thanks for that. I had tried deleting node_modules and re-running `npm install` but I hadn't tried removing package-lock.json too.
However, I have now tried and it gives the same erroneous results with repeat.for so I'll stick with the local copy of aurelia-breeze for now.

**Comment by ljtn** [comment] 2018-07-20 00:40
This seems to remain unsolved, so here is my workaround in case someone else is stuck here, and needs a quick fix.
**VM:**
<element if.bind="!updatingArray" repeat.for="item of items"></element>
**DM:**
    this.updatingArray = true;
      setTimeout(() => {
        this.items.push(item);
        this.updatingArray = false;
      },1);

As stated above - it seems like as long as the array is rerendered in its entirety it works. It appears to be the mutation of the array that triggers the issue.

**Comment by fkleuver** [comment] 2018-07-20 15:05
@ljtn could you share your package-lock.json in a gist?

**Comment by ljtn** [comment] 2018-07-20 18:47
Sorry, I was using an old version of aurelia-templating-resources (version _1.6.0_.) Works now that I updated to _1.7.1_.

**Comment by Mobe91** [comment] 2018-08-16 08:31
What is the status on this? I am using aurelia-templating-resources@1.7.1 and the issue still persists for a simple view like:
```html
<ul>
  <li repeat.for="element of elements">
	test
  </li>
</ul>
<button class="btn btn-ordami-green" click.delegate="add()">Add</button>
```
```typescript
export class MyView {
  elements = [];
  add() {
    this.elements.push("test");
  }
}
```
When I click the "Add" button once, 2 list items are produced instead of just one. No `if` involved here.

**Comment by bigopon** [comment] 2018-08-16 09:00
@Mobe91 you should also see the warning about duplicated attempt patching Array prototype if it was causing you issue. If you are using webpack, please see https://github.com/aurelia/cli/pull/906

**Comment by bigopon** [comment] 2018-08-16 09:00
@EisenbergEffect I think this can be closed

**Comment by Alexander-Taran** [comment] 2018-12-01 21:34
Definitely can be closed

**Closed** 2018-12-01 22:10 UTC
Labels: bug
