### ISSUE TITLE
Returning False from canDeactivate() causes history to be incorrect.

### ISSUE THREAD

**Issue by thughes88** [aurelia/framework#809] opened 2017-07-26 17:39 UTC
**I'm submitting a bug report**

* **Library Version:**
2.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.5.0

* **NPM Version:**
3.10.8

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.30.1

* **Browser:**
Chrome 59, Edge

* **Language:**
TypeScript 2.3.0

**Current behavior:**
Create 5 pages (a, b, c, d). Navigate from a => b => c => d. Page d has a canDeactivate() hook and a boolean to mark as dirty and a back button that calls  router.navigateBack(). Then do the following.
1. Put page d into a dirty state.
2. Click the back button 3 times. Each time the canDeactivate() returns false and the url remains on page d.
3. Now clear the dirty state. and click Back button.
4. User is sent to page a.

**Expected/desired behavior:**
I would expect the user to be navigated to page c. If the user clicks the back button on page d (when in a dirty state) 5 times, the user is taken to the first page, even thought it was still in a dirty state and should be caught by canDeactivate() and remain on page d.

It appears that even though canDeactivate() returns false, it is doing something to the history that removes the previous route each time, removing the valid history routes. I have attached a sample to show behavior
[routes.zip](https://github.com/aurelia/framework/files/1177551/routes.zip)

* **What is the motivation / use case for changing the behavior?**

**Comment by thughes88** [comment] 2017-08-11 19:37
It does seem to be related. I am seeing the same behavior. I am not using
the browser button but rather calling the navigateBack() method on the
router. The end result appears to be the same. My canDeactivate() does fire
more than once using the router navigateBack() until you reach the end of
history, because it seems to remove the last most recent history entry even
though you did not allow navigating to that page. So eventually it just
takes you out of the app. So each time you return false from
canDeactivate()  , the page you will eventually get routed to is not the
last page, but the last page - [n number of times you returned false]

**Comment by Honorato** [comment] 2017-09-01 14:59
Same behavior is happening with me.

**Comment by agouveiac** [comment] 2017-12-18 15:56
I am experiencing the same behavior.

**Comment by gama410** [comment] 2018-01-05 13:01
I have the same problem too.
It seems like a duplicate of https://github.com/aurelia/router/issues/528 which has been assigned to @davismj

**Comment by davismj** [comment] 2018-01-11 10:28
@EisenbergEffect can be closed as dupe

**Closed** 2018-01-11 10:31 UTC
