### ISSUE TITLE
Error messages gone after update

### ISSUE THREAD

**Issue by maxgrv** [aurelia/framework#166] opened 2015-07-09 07:07 UTC
After the last update (0.13.1), if there is an error, for example during a "activate" or "attached" call, no error is logged in the console. Should we change our Aurelia config? Currently we use:

     aurelia.use.history()
          .defaultBindingLanguage()
         .defaultResources()
         .router()
         .eventAggregator()
         .developmentLogging()

**Comment by decademoon** [comment] 2015-07-10 02:20
Yep this is affecting me also. I also get error messages like:

> ERROR [app-router] Router navigation failed, and no previous location could be restored.

which usually means an exception was raised when trying to import a module because of a fault in the module code.

It's easy to reproduce; the following code results in the above error message instead of the original exception:

```javascript
import ...

foo.bar();  // error because foo is undefined

export class MyViewModel { ... };
```

**Comment by samirbr** [comment] 2015-07-14 16:44
I had same error message. I updated Aurelia again and the problem  was solved.

    jspm install aurelia-animator-css aurelia-binding aurelia-bootstrapper aurelia-dependency-injection aurelia-framework aurelia-http-client aurelia-router aurelia-event-aggregator aurelia-history-browser     aurelia-loader-default aurelia-loader aurelia-metadata aurelia-route-recognizer aurelia-templating-binding aurelia-templating-resources aurelia-templating-router aurelia-templating aurelia-logging aurelia-task-queue aurelia-history aurelia-path

**Comment by EisenbergEffect** [comment] 2015-07-14 16:48
I'm closing this here. We have made a small improvement, but we are tracking this issue on the router with high priority. You can follow it here: https://github.com/aurelia/router/issues/159

**Closed by EisenbergEffect** 2015-07-14 16:48 UTC
