### ISSUE TITLE
Auto compile manually added custom elements 

### ISSUE THREAD

**Issue by olanod** [aurelia/framework#61] opened 2015-03-04 12:13 UTC
I'm transformimg [this discussion](https://gitter.im/Aurelia/Discuss?at=54f6efeb8f03d0fd57baa75f) into an issue.  
Having created an aurelia custom element e.g. `my-element` when I try to `document.createElement('my-element')` or `someDomElement.innerHTML = "<my-element></my-element>"` I expect the inserted element, if it's an aurelia custom element, to be compiled by the framework and have its behaviors, shadowDom, etc. to work as when I use it normally inside the framework.

**Comment by olanod** [comment] 2015-03-04 12:20
Possible solutions that I can think of right now as posted on the discussion are allowing the use of `document.registerElement` or using `MutationObserver` on the `document.body` to listen for aurelia custom elements additions and then compiling those elements.

**Comment by kplatter** [comment] 2015-04-20 15:34
Duplicate of dynamic-behavior custom attribute #38 in aurelia/templating-resources

https://github.com/aurelia/templating-resources/issues/38

**Comment by EisenbergEffect** [comment] 2015-10-24 04:45
Closing this as a duplicate.

**Closed by EisenbergEffect** 2015-10-24 04:45 UTC
Labels: duplicate
