### ISSUE TITLE
using setRoot fails to employ the router after the first call

### ISSUE THREAD

**Issue by davismj** [aurelia/framework#212] opened 2015-09-22 10:11 UTC
```
Aurelia.setRoot('a') // a is called, its router is instantiated properly
Aurelia.setRoot('b')
Aurelia.setRoot('a') // a is called but its router-view is empty
```

**Comment by WisdomCorp** [comment] 2015-10-16 16:23
Any update on this issue?

**Comment by davismj** [comment] 2015-10-22 10:31
@EisenbergEffect @bryanrsmith if someone can point me in the right direction, i'd be glad to take a look

**Comment by EisenbergEffect** [comment] 2015-10-22 13:34
@davismj I'm not sure what the issue could be off the top of my head. Places to look would be the Aurelia type in the Aurelia-framework repo, the CompositionEngine in the Aurelia-templating repo, the Router in the Aurelia-router repo and the RouterView in the Aurelia-templating-router repo. It's probably not in the CompositionEngine though.

**Comment by davismj** [comment] 2015-11-11 13:04
So there seems to be a lot of issues in a lot of different places here. If I were to fix it, I would likely disrupt the original design of the router if not entirely break components I'm not aware of. Instead of submitting a pull request, I will describe the situation and highlight the relevant source code.

## Problem Overview
The high level is that `app.setRoot()` behaves as if it is simply hiding one root and displaying another in its place, as **there is no deactivation of any existing viewModels, routers, or the history module before activating the new root.** However, this is not what is actually happening the entire old root is completely removed from the DOM even though all of the removed components still believe they are actively composed into the DOM.

## Relevant Code

The core issue is that, on first activate of a root with a router, the `activate()` and `configRouter()` are both called (from the [registerViewPort()](https://github.com/aurelia/router/blob/master/src/app-router.js#L47) method) which then calls `loadUrl()` and adds a navigation instruction to the queue. On the second activate however, neither `activate()` nor `configRouter()` are called because both the `isActive` and `isConfigured` flags are active.

The next issue is that, assuming the above issue is fixed, the router has no idea that its contents have been removed from the DOM entirely. If the router were to receive a navigation instruction, it would often find that the instruction is currently activated, resulting in an `activationStrategy.noChange` set within [`_buildNavigationPlan()`](https://github.com/aurelia/router/blob/master/src/navigation-plan.js#L23).

## Potential Solutions
1. The most reasonable solution seems to be **to process a full deactivation on the old root before activating the new root.** 
*Pros:* This is consistent, predictable, logical, and maintainable. 
*Cons:* In place switching actually seems like it might be the desired behavior.

2. If in place switching is desired, then it might be best **to instruct Aurelia to keep a copy of each root-level app hidden in the DOM when setting root.** 
*Pros:* This would work well in the use case where state would need to be preserved between various apps. 
*Cons:* Does nothing for apps with independent routers, which might be a more common use case, may lead to performance degradation when using multiple complex apps.

3. Rewrite parts of the Aurelia framework to leverage the router, such that **every app has a hidden root level router that sets the root.** 
*Pros:* Consistent with expected behavior since the behavior of the router is well known, reduces complexity of the `app.setRoot()` since it leverages existing code, introduces all the extensibility of the router. 
*Cons:* Could be a substantial rewrite with breaking changes.

4. Another alternative would be **to introduce (a) new flag(s) into the application to differentiate between a routing navigation and a setRoot navigation.** 
*Pros:* Has the least impact on the current functionality set of the framework as it would consist entirely of new additions. 
*Cons:* Hackish, probably time consuming, likely introduces a lot of complexity.

**Comment by EisenbergEffect** [comment] 2015-11-11 16:38
Thanks for looking into this @davismj I don't think we can fix it before next week's beta...but I think it can be fixed without breaking changes after the beta. Some changes in the setRoot to track some things and maybe some internal changes to the router's plugin configuration.

**Comment by avitex** [comment] 2015-11-23 23:33
Looking forward to the fix :+1:
My application depends on this functionality.

**Comment by wshayes** [comment] 2015-11-23 23:52
My application does too!  Several sections of my application need a different root page.  Thanks @davismj for digging into it.  Hopefully the fix won't take long to sort out.

**Comment by davismj** [comment] 2015-11-24 05:54
@bryanrsmith @EisenbergEffect My application depends on it as well. Perhaps we can get a conversation going about how we want to handle this.

**Comment by WisdomCorp** [comment] 2015-11-24 06:04
@EisenbergEffect In your channel 9 demo, you are going to main.js to change the root manually to show each demo. If this bug is fixed then all demo can be listed as a child route (as available in skeleton app) and you can just click on different option without resorting to change code manually :) 

Now beta is released I hope you can look into it as mentioned by you above. As its a very powerful concept and will add lot of flexibility for us. Thank you

**Comment by banazak** [comment] 2015-12-10 15:44
Hi @EisenbergEffect  Any update on this?

**Comment by davismj** [comment] 2015-12-14 13:57
Bump.

**Comment by 32graham** [comment] 2015-12-17 17:21
I'm seeing this too. Using Polymer's `<paper-drawer-panel>` with a `<router-view>` as the main content to host our Aurelia app. There is no easy way to completely get rid of the drawer for login, so I thought I could use `auerlia.setRoot("./src/accounts/user-login")` to get rid of the navigation stuff. Works great until I log out and log back in.

**Comment by EisenbergEffect** [comment] 2015-12-29 22:04
Can someone put together for me an absolutely simplest possible repro? @davismj If you can send me some src files that I can drop into the nav skele to replicate the problem, I can work on this this week myself.

**Comment by davismj** [comment] 2015-12-29 22:14
Take a look at http://davismj.github.io/sentry/. Source at http://github.com/davismj/sentry/

**Comment by EisenbergEffect** [comment] 2015-12-29 22:28
I want something really simple. Should be possible with four components: two roots, and two routed to pages, correct?

**Comment by davismj** [comment] 2015-12-29 22:47
You only need one route on one of the roots. Yes.

**Comment by EisenbergEffect** [comment] 2015-12-30 18:02
I believe I can make this work without too much trouble. Would it be acceptable to require the following code?

```
this.router.deactivate();
this.router.reset();
this.aurelia.setRoot('app2');
```

Where `this.router` references the `AppRouter`.
Let me know.

**Comment by davismj** [comment] 2015-12-30 19:23
Routers are set on viewModels in the `configureRouter` function. Since they are intrinsic to viewModels, shouldn't they be automatically deactivated when the viewModel is deactivated?

**Comment by EisenbergEffect** [comment] 2015-12-30 19:27
Router deactivation basically turns off routing, so no, I wouldn't think so.

**Comment by EisenbergEffect** [comment] 2015-12-30 19:29
Also, the view model doesn't need to retain a reference to the router. The routing system makes no assumption that there is a router property.

**Comment by schatekar** [comment] 2016-01-03 11:37
@EisenbergEffect Is this issue still being fixed or can I use the following code from one of your previous comments?

```
this.router.deactivate();
this.router.reset();
this.aurelia.setRoot('app2');
```

**Comment by EisenbergEffect** [comment] 2016-01-03 11:40
It hasn't been fixed because the `reset` method doesn't exist. We think we can also remove the need to write the first two lines of code so only a call to `setRoot` is needed. It shouldn't take long to fix and we could get it into this week's release, but I didn't really get any feedback from other people here. I was waiting a bit to see if there were any other comments.

**Comment by schatekar** [comment] 2016-01-03 12:12
It would be great if we can get it down to 1 line. I am anxiously waiting for this fix. 

A related question - In my use case, I have a separate router for `app2`. Would calling `setRoot('app2')` also navigate to default route automatically or I would need to call `navigateToRoute` myself?

**Comment by davismj** [comment] 2016-01-03 13:50
There isn't technically a default route. If you mean the '/' route, if you
navigate while at that route, it should activate that route for both roots.

If you have 'mapUnknownRoute' to your '/' route, that would cover almost
every case.

**Comment by 32graham** [comment] 2016-01-05 13:53
```
this.router.deactivate();
this.router.reset();
this.aurelia.setRoot('app2');
```

Seems acceptable to me @EisenbergEffect. For my use case I would want to use all 3 lines. It seems possible however that someone might not need/want the first two lines, so I think this is a good solution.

**Closed** 2016-01-05 16:59 UTC
Labels: bug, enhancement

**Comment by EisenbergEffect** [comment] 2016-01-05 17:00
The next set of patch releases, hopefully coming this week, will include this fix. There's no need to call deactivate or reset. Successive calls to setRoot will detect the presence of the router on the previous root view model and deactivate/reset it automatically.

**Comment by davismj** [comment] 2016-01-05 17:06
@EisenbergEffect You're a rockstar. :guitar:

**Comment by EisenbergEffect** [comment] 2016-01-05 17:07
Really sorry this took so long.

**Comment by schatekar** [comment] 2016-01-06 09:50
Thanks @EisenbergEffect 

It is things like these that made me fall in love with Aurelia instantly.

**Comment by vcardins** [comment] 2016-03-02 11:58
This issue seems to be happening again. Just having a similar situation after the latest update. I'll dig into and comment here.

**Comment by davismj** [comment] 2016-03-03 21:57
Any further info, @vcardins ?

**Comment by vcardins** [comment] 2016-03-04 01:29
I'm putting in place a demo project as suggested by Rob, I should upload in a day or two.

**Comment by cehoffman** [comment] 2016-03-06 06:15
@vcardins I noticed setRoot wasn't reinitializing the router and the root cause came down to me not saving the router instance from **configureRouter** for the first setRoot module as `this.router`. Once I saved the instance in that property, the changes in 0f83b9b kicked in.

**Comment by vcardins** [comment] 2016-03-06 08:14
@cehoffman, thanks for looking at. has this fix been published yet?

**Comment by vcardins** [comment] 2016-03-10 03:01
I out in place a small repo, based on skeleton-es2016 to reproduce my issue https://github.com/vcardins/skeleton-es2016-multiple-root. 
(For some reason the AuthorizeStep is not working, so I redirected manually)
Steps ...
1. main.js
`aurelia.start().then(() => aurelia.setRoot('bootstrapper'));` 
2. bootstrapper.js
   2.1 Configure the routes: `this.appRouterConfig.configure();`
   2.2 Check's whether the user is logged in and set the proper root: `this.aurelia.setRoot(root)`
3. login.js:
   After logging in, it sets again the root:
   ``` 
  this.authService.authenticate(this.username, this.password).then((response)=>{
        self.aurelia.setRoot('app').then(() => {
          //self.router.navigate('', {});
        });
      })
      .catch(err=>{
        console.error(err.message);
      });
  }
   ```
4. logout.js
 ```this.authService.logout().then(response=>{
            self.aurelia.setRoot('public').then(() => {
             //self.router.navigate('login', {});
            });
  	});
```

**Comment by vcardins** [comment] 2016-03-10 03:34
@davismj Please, see my previous post. Thank you !!

**Comment by fabioluz** [comment] 2016-04-11 13:20
@cehoffman I had this same problem today. After read your comment I realised that I was not saving the router instance in the login root component. Everything worked after saving the router instance in the `this.router` property.

**Comment by HIRANO-Satoshi** [comment] 2016-05-21 08:22
Thank you very much, @davismj
