### ISSUE TITLE
click.delegate event sometimes not triggered

### ISSUE THREAD

**Issue by bekite** [aurelia/framework#29] opened 2015-02-07 18:14 UTC
I have the following repeater in my template:
```
<button click.delegate="$parent.select(nr)" repeat.for="nr of nrs">${nr}</button>
```
If I define nrs as a getter:
```
class MyClass
  get nrs() {
    return [1, 2, 3, 4, 5]
  }
  select() {...}
}
```
When clicking on a button, the select function is sometimes not called.
Everything works just fine, if I define nrs in the constructor.

**Comment by kolarski** [comment] 2015-02-08 15:42
Can I mention also that I couldn't find any documentation on $parent. and lost me a good couple of hours :)

**Comment by Hendrixer** [comment] 2015-02-09 05:06
Yea, what is `$parent`?

**Comment by mvpspl619** [comment] 2015-02-11 13:36
Would you have a working example hosted somewhere so we can get our hands dirty ?

**Comment by mvpspl619** [comment] 2015-02-11 13:48
I happened to get the code from your repo and reproduced the scenario. Looks like there is a bigger problem behind why sometime your delegated method is not called. 

DOM is being constantly updated in an infinite loop. I am working on reproducing this issue somewhere shareable.

**Comment by mvpspl619** [comment] 2015-02-11 14:06
https://github.com/aurelia/binding/issues/27

Created an issue. Once this is fixed, if we can reproduce this problem we can fix it. But I believe the inconsistency you face for that function call is because of the above issue.

**Comment by jdanyow** [comment] 2015-04-30 19:16
@bekite can this be closed?  

One thing you might change is the `nrs` property.  A computed property used with data binding shouldn't return new array instances each time it's accessed.  More info [here](https://github.com/aurelia/documentation/blob/master/English/docs.md#adaptive-binding)

**Comment by jdanyow** [comment] 2015-05-28 22:21
Closing- we can re-open if it turns out this is unresolved.

**Closed by jdanyow** 2015-05-28 22:21 UTC
Labels: question
