### ISSUE TITLE
"Out of stack space" error in IE (due to importing resources)

### ISSUE THREAD

**Issue by flieks** [aurelia/framework#214] opened 2015-09-24 14:51 UTC
Hi,

I'm getting this error only in IE.
`Unhandled promise rejection Error: Out of stack space`
![capture6](https://cloud.githubusercontent.com/assets/5032389/10076354/752c8cd4-62db-11e5-9225-b9048a78f2d9.JPG)
@acidbluebriggs has the error when putting template in template tags like the aurelia dialog footer does [here](https://github.com/aurelia/dialog/blob/master/src/dialog-footer.html).
But i didn't use the dialog nor template in template tags.
It has something to do with importing resources (see first screenshot). 

My app.html/js isn't even loaded yet. The loader.html is not used in my resource/index.js but in a require in a resource (autocomplete.html see first screenshot). 

@CharlesPockert also had the same error (don't know his cause).

Greetings
Felix

**Comment by charlespockert** [comment] 2015-09-24 15:23
Dupe of this issue methinks: https://github.com/aurelia/templating/issues/169

**Closed** 2015-09-24 16:30 UTC
Labels: duplicate

**Comment by flieks** [comment] 2015-09-24 22:01
sorry guys, i didn't look good enough,
It seems i was using a template in a template after all.
I just replaced this:
`<template show.bind="$parent.propnames" replaceable part="item-template">`
by this
`  <div show.bind="$parent.propnames" replaceable part="item-template">`
which fixed it
thanks for help
