### ISSUE TITLE
Two-way binding calls setter when property was updated from code

### ISSUE THREAD

**Issue by mhoyer** [aurelia/framework#30] opened 2015-02-07 18:27 UTC
Think of this simple demo:

```
<!-- app.html -->
<template>
  <input type="checkbox" checked.bind="isChecked">
  <button click.delegate="activateCheckedState()">set checked</button>
</template>
```

```
<!-- app.js -->
export class App {
  constructor() { 
    this._isCheckedState = false;
  }

  activateCheckedState() {
    this.isChecked = true; // #1 will call the isChecked setter first and once
  }

  set isChecked(value) {
    console.log("Set: " + value);
    this._isCheckedState = value;
  }

  get isChecked() { 
    return this._isCheckedState; // #2 dirty-checking will find updated value and updates UI
  }
}
```

Running this will result in two console log entries:

```
Set: true
Set: true
```

When clicking the button:

0. `activateCheckedState` calls the `isChecked` setter directly
0. `isChecked` setter in turn updates inner `_isCheckedState`
0. dirty-checking is *watching* the `isChecked` getter and finds a new value after some time (see #25)
0. this updates the actual binding. Hence the check box gets checked.
0. but this again publishes a notification to call the `isChecked` setter 

This is confusing IMHO.

**Comment by mvpspl619** [comment] 2015-02-11 12:40
The calling of isChecked's setter the second time might be because of the way binding works here. I am thinking the following is the reason for the second call to setter.

dirty-checking -> find a change -> updates the view -> updates the property on view-model. 

By design, if Aurelia doesn't update the value separately on view and view-model, the second call should never happen.

**Comment by mvpspl619** [comment] 2015-02-11 13:24
Turns out, the call to `activateCheckedState()` is not updating the DOM. But dirty checking is doing the DOM updation. So if you somehow disable dirty checking, you would actually see the checkbox not being checked even if you click on the button until and unless dirty checking kicks off and finds there is change and update the UI.

**Comment by jdanyow** [comment] 2015-05-02 10:14
@mhoyer this doesn't seem to be an issue in the latest release:
http://screencast.com/t/EV4ZPlQbUB

Can this be closed?

**Comment by EisenbergEffect** [comment] 2015-05-09 05:31
Looks like it's working. Closing for now.

**Closed by EisenbergEffect** 2015-05-09 05:31 UTC
Labels: question
