### ISSUE TITLE
Very long startup time of Aurelia apps in Microsoft Edge (20+ seconds)

### ISSUE THREAD

**Issue by kollster** [aurelia/framework#257] opened 2015-11-30 13:47 UTC
Aurelia apps have very long startup time in Microsoft Edge. Take Aurelia Docs (http://aurelia.io/docs.html) and a freshly yeoman generated project with generator-aurelia - both apps have a startup time of over 20 seconds in Edge, whereas the startup time in Chrome is under 4 seconds.

**Comment by EisenbergEffect** [comment] 2015-11-30 14:51
I can't say I've ever seen a 20 second startup time on any Aurelia app on any platform or browser. Not even my phone takes that long. If the app is unbundled, then that is going to make startup slower. If you have the dev tools open, that will often make the startup much, much slower.

One of our focuses in the beta timeframe is on performance, so we do expect to be improving startup times through a variety of techniques. I'm going to close this issue since we are already tracking this elsewhere.

**Closed by EisenbergEffect** 2015-11-30 14:51 UTC

**Comment by kollster** [comment] 2015-11-30 16:08
The 20+ seconds startup time can be reproduced on Edge for Windows 10 tested on multiple desktop and mobile devices. This is also true without enabling developer tools. The issue can be quite easily reproduced by navigating to http://aurelia.io/docs.html with Edge on a Windows 10 device. Where is this issue being tracked elsewhere?

**Comment by Thanood** [comment] 2015-11-30 18:39
I can confirm that. It takes around 18 seconds on my machine, Windows 10, Edge opened without dev tools.

Now opened with dev tools, here's the network graph - maybe it helps:
![image](https://cloud.githubusercontent.com/assets/677826/11480682/17ee7daa-9799-11e5-8a43-aba57a0d4a2f.png)

I'm really not good with interpreting the profiler in IE/Edge, but there seem to be tons of "window.timeout"s and "readyStateChange" listeners from system.js.

Most of the time seems to be between load steps of aurelia.js, main.js ans app-build.js (all with loading http://aurelia.io/docs.html)..

**Comment by dpinart** [comment] 2015-11-30 19:37
I can't see such a long start time. In my laptob it took less than 4 secons with Windows + Edge. I need to open devtools, otherwise the page doesn't load.

I don't know if it helps, but I've seen many differences in load time depending on the labtop. One of my collegues claims for long start times in his computer with windows 8 + chrome while me and others, in the same network can see 'normal' start times.

**Comment by The1nternet** [comment] 2015-11-30 20:04
I also cannot get the docs to load in Edge on Windows 10 unless I have the devtools open.  Sometimes, even it won't even load with the devtools open.  I'm not sure the exact repro steps, however...

**Comment by kollster** [comment] 2015-12-01 08:39
I believe there may be a serious issue here regarding Edge support - can this issue be reopened?

**Comment by jwtvh** [comment] 2016-04-21 10:16
Issue still exist, please reopen

**Comment by alsoicode** [comment] 2016-04-21 10:27
I'm seeing the same issue.

**Comment by dpinart** [comment] 2016-04-21 10:53
For me, switching from JSPM/Systemjs to Webpack fix the issue. I now can run my aurelia apps on any browser (chrome, edge, firefox, safari) and even on any device (androis/ios/windows phone) as phonegap apps

**Comment by stsje** [comment] 2016-04-21 11:06
Our web app. loads in under a second using Edge and the following stack:
Bluebirdjs, Systemjs, Jspm

You will be having load time issues if you haven't included bluebirdjs before systemjs in your index file. The performance improvements webpack would bring us were very minimal, if even any at all, when we tested it out on our application. For us it made no sense to make the switch to webpack, since systemjs handled it just fine (medium-large sized app.)

**Comment by devmondo** [comment] 2016-04-21 12:32
i fully agree with @stsje, we tested Webpack and saw minimal advantage, not to mention some lacking features that are important to us like dynamic modules creation.

just as @stsje  said, make sure you include bluebird before System.js in your index.html, also we faced strange issue that caused IE 11 to freeze if we include bluebird,  to solve the issue we included the minified version 
https://github.com/systemjs/systemjs/issues/1220#issuecomment-211098947

and voila everything works. hope this helps.

**Comment by dpinart** [comment] 2016-06-22 07:45
I'm considering getting back to systemjs from webpack (as @EisenbergEffect explained webpack has some constraints I can't longer live with) but I need to support edge and I'm a bit concerned cause I'm still seeing some issues. For example, there are some aurelia doc pages like http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/bundling-your-app-for-deploy do not load on edge unless I have dev tools opened. I can see above page is including bluebird.min before systemjs and it's still having probelms on edge. Not sure if there are some known external libraries, combinations, deps,... that makes apps stop working on edge

**Comment by atsu85** [comment] 2016-06-22 13:32
@EisenbergEffect,
1) 
> I'm considering getting back to systemjs from webpack ... webpack has some constraints I can't longer live with

Is there some documentation that explains the pros and cons of different loaders?

2) is this known issue:
> there are some aurelia doc pages like http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.2.4/doc/article/bundling-your-app-for-deploy do not load on edge unless I have dev tools opened

**Comment by EisenbergEffect** [comment] 2016-06-22 13:39
@atsu85 You may want to give our new CLI a try. Wait a bit longer for the announcement today about that. We'll also have a new release of the docs, which we are transforming to a developer hub. That is built with the CLI and shouldn't exhibit these issues.
