### ISSUE TITLE
deactivate() does not invoked after navigate to other router module.

### ISSUE THREAD

**Issue by xiwc** [aurelia/framework#563] opened 2016-08-20 03:13 UTC
**I'm submitting a bug report**

* **Library Version:**
"aurelia-framework": "^1.0.0-rc.1.0.0",

**Please tell us about your environment:**
* **Operating System:**
Windows [7|10]

* **Node Version:**
v4.4.2

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
webpack 1.13.1

* **Browser:**
Chrome 52.0.2743.116 m

* **Language:**
ESNext

**Current behavior:**
when i switch router.
1. `#/server/disk  -> #/server/other`  deactivate() is invoked normally
2. `#/server/disk -> #/network/other` deactivate() is not invoked normally

**Comment by guilhermewaess** [comment] 2016-09-14 03:01
Are you using layouts?
I have the same problem, but with attached() <- attached() never calls when I using layouts :(

**Comment by alpox** [comment] 2016-09-14 07:43
Seems to be a duplicate of https://github.com/aurelia/templating-router/issues/34

**Comment by jdanyow** [comment] 2016-09-26 12:04
Issue moved to [aurelia/router #411](https://github.com/aurelia/router/issues/411) via [**ZenHub**](https://www.zenhub.com/)

**Closed by jdanyow** 2016-09-26 12:04 UTC
